### ISSUE TITLE
Styleguide build throws errors

### ISSUE THREAD

**Issue by mkampmey** [vue-microfrontends/styleguide#6]
When executing `npm run build` I get this error.
```
(1:1) Unknown word

> 1 | var api = require("!../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js");
    | ^
  2 |             var content = require("!!../node_modules/css-loader/dist/cjs.js!./global.css");
  3 |

 @ ./src/global.css 2:26-180
 @ ./src/vue-mf-styleguide.js
```
The issue does not appear when removing the `style-loader` rule from webpack config.

**Comment by joeldenning** [comment]
Hi @mkampmey - try using `yarn` instead of `npm`. This project has a yarn.lock file that ensures correct versions of dependencies.

**Comment by mkampmey** [comment]
Perfect, thank you.
